name: Build OMtoSMConverter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build with MSBuild
      run: msbuild OMtoSMConverter.sln /p:Configuration=Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OMtoSMConverter
        path: OMtoSMConverter\bin\Release\
